config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

  root to: 'trendingmovies#index'
  resources :trendingmovies
  resources :trendingshows
  resources :users
  resources :movies
  resources :viewedmovies

  get  '/searchmovies' => 'searchmovies#form'
  post '/searchmovies/lookup' => 'searchmovies#lookup'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to 'Movie Guide', root_path, class: "navbar-brand" %>
          <div >
            <% if @current_user.present? %>
              <h5><%= link_to @current_user.name, @current_user , class: "welcomeuser"%></h5>
            <% end %>
          </div>
        </div>


        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <% if @current_user.present? %>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Search Movies', searchmovies_path %></li>
              <li><%= link_to 'Favourites', movies_path%></li>
              <li><%= link_to 'Watched List', viewedmovies_path %></li>

              <li><%= link_to 'Logout', login_path, method: :delete %></li>
            <% else %>
              <li>  <%= link_to 'Home', root_path %></li>
              <li><a href="#about">About Us</a></li>

              <li>  <%= link_to 'Login', login_path %></li>
              <li>  <%= link_to 'SignUp', new_user_path %></li>

            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <br>
    <br>
    <br>
    <br>


      <!-- <h1> H</h1>
     <span class="glyphicon glyphicon-heart logo-small"></span> -->
    <%= yield %>

  </body>
</html>